### ISSUE TITLE
light mu factor can go nan

### ISSUE THREAD

**Issue by fotlogo** [hiroaki-santo/deep-near-light-photometric-stereo#1]
@ model_near_ps.py line 204 it is needed to add something like 'dot = torch.clamp(1e-5, 1.)' to avoid having a negative power (it can very well happen for points far away from the center of the image if S_dir is not [0,0,1]) to cause a nan to occur that would crash ttraning

**Comment by hiroaki-santo** [comment]
Thank you for your bug report.
